apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "postgres-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postgres-operator.name" . }}
    helm.sh/chart: {{ include "postgres-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: {{ include "postgres-operator.fullname" . }}
      labels:
        app.kubernetes.io/name: {{ include "postgres-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: postgres-operator-yaml
              mountPath: /operator
            - name: kubeconfig
              mountPath: /kubeconfig
          env:
            - name: RUN_TIME
              value: {{ .Values.runTime | quote }}
            - name: KUBERNETES_NAMESPACE
              value: "pgo"
            - name: BASE_KUBERNETES_NAMESPACE
              value: "pgo"
            - name: BASE_KUBERNETES_NAMESPACE_SERVICE_ACCOUNT
              value: "pgo"
            - name: BASE_KUBERNETES_NAMESPACE_SERVICE_ACCOUNT_TOKEN
              value: "eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJwZ28iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoicGdvLXRva2VuLTcycWNjIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InBnbyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjJiMDBlYmQyLTcyODktMTFlYS1hMjlmLTQyMDEwYTgwMDFmNSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpwZ286cGdvIn0.aRgytFGTG-PuC7D5OmL1MVGipu7ZRT8FGnRDqoL6QCDQavJT1lA-hh-BQ1g-tvyplKMKamqprSGVwW8JfP4r7x97gWlcAW4Wfbl_qcqLe8XokWBU9nuK5QZBtRw4mZWCWVLs5dGX4sGjTqhJJ9dHEaeKH07AndRybESfOpdxgWXeCiizrDaZH8Hv6eRCNuDjn1v3NYpl-G4DDLxaiP9C7DAoUpzZ9obMGIpKizGs-18IrttFa9kyjsYApSM-gQ_QCvd-pz15w1tqpE0VphU8lKzJJBiwvb6Deh_GBvP1RJX0sVKFdPo-y_bOWXIb84jEks_cRE6gDkDL5k6g5J8buA"
            - name: OPERATOR_COMMAND
              value: {{ .Values.command | default "deploy" | quote }}
            - name: OPERATOR_IMAGES
              value: {{ .Values.image.repository | quote }}
            - name: OPERATOR_POD
              value: {{ .Values.podName | default "percona-xtradb-cluster-operator" | quote }}
            - name: BACKUP_NAME
              value: {{ .Values.backupName | default "" | quote }}
            - name: PERCONA_OPERATOR_VERSION
              value: {{ .Values.perconaOperatorVersion | default "1.3.0" | quote }}
            - name: PERCONA_API_VERSION
              value: {{ .Values.perconaApiVersion | default "v1-3-0" | quote }}
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName | quote }}
      volumes:
        - name: postgres-operator-yaml
          configMap:
            name: {{ include "postgres-operator.fullname" . }}
        - name: kubeconfig
          configMap:
            name: {{ include "postgres-operator.fullname" . }}-kubeconfig
      restartPolicy: Never
