apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-operator.fullname" . }}-conf
  labels:
    app.kubernetes.io/name: {{ include "postgres-operator.name" . }}-conf
    helm.sh/chart: {{ include "postgres-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  pgo.yaml: {{ toYaml .Values.pgoYaml | indent 2 }}