apiVersion: v1
data:
  permissions: "{{ .Values.pgo_admin_perms | b64encode  }}"
  rolename: {{ .Values.pgo_admin_role_name | b64encode  }}
kind: Secret
metadata:
  labels:
    pgo-created-by: bootstrap
    pgo-pgorole: "true"
    rolename: {{ .Values.pgo_admin_role_name }}
    vendor: crunchydata
  name: pgorole-{{ .Values.pgo_admin_role_name }}
  namespace: {{ .Values.pgo_operator_namespace }}
type: Opaque
