apiVersion: v1
data:
  password: {{ .Values.pgo_admin_password | b64enc  }}
  username: {{ .Values.pgo_admin_username | b64enc  }}
  roles: {{ .Values.pgo_admin_role_name | b64enc }} 
kind: Secret
metadata:
  labels:
    pgo-created-by: bootstrap
    pgo-pgouser: "true"
    username: {{ .Values.pgo_admin_username }}
    vendor: crunchydata
  name: pgouser-{{ .Values.pgo_admin_username }}
  namespace: {{ .Values.pgo_operator_namespace }}
type: Opaque

